[client]
showSidebarNavigation = false

[theme]
base = "light"
primaryColor = "#005BAC"
backgroundColor = "#F3F7FB"
secondaryBackgroundColor = "#ffffff"
textColor = "#152D45"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true
